export interface AnimeQuote {
  id: string;
  quote: string;
  character: string;
  anime: string;
  animeRomaji?: string;
  japaneseQuote?: string;
  category: 'wisdom' | 'battle' | 'freedom' | 'determination' | 'emotion' | 'philosophy';
  themeColor: string;
  characterAvatar?: string;
  year?: number;
}

export const ANIME_QUOTES_DATABASE: AnimeQuote[] = [
  {
    id: 'luffy-1',
    quote: "If you don't take risks, you can't create a future!",
    character: 'Monkey D. Luffy',
    anime: 'One Piece',
    japaneseQuote: '命を懸けなきゃ未来は拓けない！',
    category: 'determination',
    themeColor: 'from-amber-500 to-rose-500',
    year: 1999,
  },
  {
    id: 'zoro-1',
    quote: "Scars on the back are a swordsman's shame.",
    character: 'Roronoa Zoro',
    anime: 'One Piece',
    japaneseQuote: '背中の傷は剣士の恥だ',
    category: 'battle',
    themeColor: 'from-emerald-500 to-teal-600',
    year: 1999,
  },
  {
    id: 'frieren-1',
    quote: "It's the memories of the journey, not just the destination, that give life its warmth.",
    character: 'Frieren',
    anime: "Frieren: Beyond Journey's End",
    japaneseQuote: '旅の記憶こそが、生に温もりを与える。',
    category: 'wisdom',
    themeColor: 'from-cyan-400 to-indigo-500',
    year: 2023,
  },
  {
    id: 'himmel-1',
    quote: "Even if it's just a fleeting moment, if it brings a smile, it wasn't in vain.",
    character: 'Himmel the Hero',
    anime: "Frieren: Beyond Journey's End",
    japaneseQuote: 'ほんの些細なことでも、君を笑顔にできたなら無駄じゃない。',
    category: 'emotion',
    themeColor: 'from-sky-400 to-blue-600',
    year: 2023,
  },
  {
    id: 'gojo-1',
    quote: "Throughout heaven and earth, I alone am the honored one.",
    character: 'Satoru Gojo',
    anime: 'Jujutsu Kaisen',
    japaneseQuote: '天上天下 唯我独尊',
    category: 'battle',
    themeColor: 'from-purple-500 to-cyan-400',
    year: 2020,
  },
  {
    id: 'itadori-1',
    quote: "I don't want to regret the way I lived. I want to save people so when I die, I'm surrounded by friends.",
    character: 'Yuji Itadori',
    anime: 'Jujutsu Kaisen',
    japaneseQuote: '生き様で後悔はしたくない。',
    category: 'philosophy',
    themeColor: 'from-rose-500 to-orange-500',
    year: 2020,
  },
  {
    id: 'eren-1',
    quote: "If you win, you live. If you lose, you die. If you don't fight, you can't win!",
    character: 'Eren Yeager',
    anime: 'Attack on Titan',
    japaneseQuote: '勝てば生きる、負ければ死ぬ。戦わなければ勝てない！',
    category: 'freedom',
    themeColor: 'from-amber-600 to-rose-700',
    year: 2013,
  },
  {
    id: 'erwin-1',
    quote: "My soldiers, rage! My soldiers, scream! My soldiers, fight!",
    character: 'Erwin Smith',
    anime: 'Attack on Titan',
    japaneseQuote: '我が兵士よ怒れ！我が兵士よ叫べ！我が兵士よ戦え！',
    category: 'determination',
    themeColor: 'from-yellow-500 to-emerald-600',
    year: 2013,
  },
  {
    id: 'levi-1',
    quote: "The only thing we're allowed to do is believe that we won't regret the choice we made.",
    character: 'Levi Ackerman',
    anime: 'Attack on Titan',
    japaneseQuote: '悔いが残らない方を自分で選べ。',
    category: 'philosophy',
    themeColor: 'from-slate-500 to-emerald-600',
    year: 2013,
  },
  {
    id: 'light-1',
    quote: "I will create a new world where only kind and honest people can live.",
    character: 'Light Yagami',
    anime: 'Death Note',
    japaneseQuote: '僕が新世界の神となる。',
    category: 'philosophy',
    themeColor: 'from-red-600 to-purple-800',
    year: 2006,
  },
  {
    id: 'l-1',
    quote: "Justice will prevail, no matter what. Because I am justice.",
    character: 'L Lawliet',
    anime: 'Death Note',
    japaneseQuote: '正義は必ず勝つということを。',
    category: 'wisdom',
    themeColor: 'from-slate-600 to-blue-700',
    year: 2006,
  },
  {
    id: 'edward-1',
    quote: "A lesson without pain is meaningless. For you cannot gain anything without sacrificing something else in return.",
    character: 'Edward Elric',
    anime: 'Fullmetal Alchemist: Brotherhood',
    japaneseQuote: '痛みを伴わない教訓には意義がない。人は何かの犠牲なしに何も得ることはできない。',
    category: 'wisdom',
    themeColor: 'from-amber-500 to-red-600',
    year: 2009,
  },
  {
    id: 'mustang-1',
    quote: "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful.",
    character: 'Roy Mustang',
    anime: 'Fullmetal Alchemist: Brotherhood',
    japaneseQuote: '世の中は不完全だ。だからこそ美しい。',
    category: 'emotion',
    themeColor: 'from-orange-500 to-blue-700',
    year: 2009,
  },
  {
    id: 'madara-1',
    quote: "Wake up to reality! Nothing ever goes as planned in this accursed world. Wherever there is light, there are always shadows.",
    character: 'Madara Uchiha',
    anime: 'Naruto Shippuden',
    japaneseQuote: '現実に目覚めろ。この世の全ては思い通りにはならん。',
    category: 'philosophy',
    themeColor: 'from-red-700 to-purple-900',
    year: 2007,
  },
  {
    id: 'naruto-1',
    quote: "I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way!",
    character: 'Naruto Uzumaki',
    anime: 'Naruto',
    japaneseQuote: 'まっすぐ自分の言葉は曲げねぇ。それがオレの忍道だ！',
    category: 'determination',
    themeColor: 'from-orange-500 to-amber-400',
    year: 2002,
  },
  {
    id: 'itachi-1',
    quote: "It is not wise to judge others based on your own preconceptions and by their appearances.",
    character: 'Itachi Uchiha',
    anime: 'Naruto Shippuden',
    japaneseQuote: '人は己の知識や認識に縛られ、それを現実と呼んで生きている。',
    category: 'wisdom',
    themeColor: 'from-rose-600 to-indigo-700',
    year: 2007,
  },
  {
    id: 'jiraiya-1',
    quote: "A person grows up when he's able to overcome hardships. Protection is important, but there are some things that a person must learn on his own.",
    character: 'Jiraiya',
    anime: 'Naruto',
    japaneseQuote: '男が磨かれるのは挫折を味わった時だ。',
    category: 'wisdom',
    themeColor: 'from-emerald-600 to-red-600',
    year: 2002,
  },
  {
    id: 'tanjiro-1',
    quote: "No matter how many people you may lose, you have no choice but to go on living. No matter how devastating the blows may be.",
    character: 'Tanjiro Kamado',
    anime: 'Demon Slayer: Kimetsu no Yaiba',
    japaneseQuote: '失っても失っても生きていくしかない。どんなに打ちのめされても。',
    category: 'determination',
    themeColor: 'from-emerald-500 to-cyan-500',
    year: 2019,
  },
  {
    id: 'rengoku-1',
    quote: "Set your heart ablaze! Go beyond your limits! Grit your teeth and push forward.",
    character: 'Kyojuro Rengoku',
    anime: 'Demon Slayer: Mugen Train',
    japaneseQuote: '心を燃やせ！限界を超えろ！前を向け！',
    category: 'determination',
    themeColor: 'from-amber-500 to-red-600',
    year: 2020,
  },
  {
    id: 'spike-1',
    quote: "Whatever happens, happens.",
    character: 'Spike Spiegel',
    anime: 'Cowboy Bebop',
    japaneseQuote: '何が起ころうと、起こるべくして起こる。',
    category: 'philosophy',
    themeColor: 'from-blue-600 to-slate-700',
    year: 1998,
  },
  {
    id: 'lelouch-1',
    quote: "The only ones who should shoot are those who are prepared to be shot.",
    character: 'Lelouch vi Britannia',
    anime: 'Code Geass',
    japaneseQuote: '撃っていいのは撃たれる覚悟のある奴だけだ。',
    category: 'philosophy',
    themeColor: 'from-purple-600 to-red-700',
    year: 2006,
  },
  {
    id: 'kamina-1',
    quote: "Don't believe in the you that believes in me, and don't believe in the me that believes in you. Believe in the you that believes in yourself!",
    character: 'Kamina',
    anime: 'Tengen Toppa Gurren Lagann',
    japaneseQuote: 'お前が信じる、お前を信じろ！',
    category: 'determination',
    themeColor: 'from-rose-500 to-amber-500',
    year: 2007,
  },
  {
    id: 'okabe-1',
    quote: "No one knows what the future holds. That's why its potential is infinite, as this meeting itself shows.",
    character: 'Rintaro Okabe',
    anime: 'Steins;Gate',
    japaneseQuote: '未来のことは誰にも分からない。だからこそ無限の可能性がある。',
    category: 'wisdom',
    themeColor: 'from-cyan-500 to-indigo-600',
    year: 2011,
  },
  {
    id: 'kurisu-1',
    quote: "Time is passing so fast. It feels like the present is already the past.",
    character: 'Makise Kurisu',
    anime: 'Steins;Gate',
    japaneseQuote: '時間は不可逆。だからこそ一瞬一瞬が尊い。',
    category: 'emotion',
    themeColor: 'from-rose-500 to-purple-600',
    year: 2011,
  },
  {
    id: 'thorfinn-1',
    quote: "You have no enemies. No one has any enemies. There is no one in this world that you need to hurt.",
    character: 'Thors Snorresson',
    anime: 'Vinland Saga',
    japaneseQuote: 'お前に敵などいない。誰にも敵などいないんだ。',
    category: 'wisdom',
    themeColor: 'from-emerald-600 to-slate-700',
    year: 2019,
  },
  {
    id: 'guts-1',
    quote: "If you're always worrying about crushing the ants beneath you... you won't be able to walk.",
    character: 'Guts',
    anime: 'Berserk',
    japaneseQuote: '踏みつぶす蟻のことまで気にしてたら、歩けやしねえよ。',
    category: 'battle',
    themeColor: 'from-slate-700 to-red-800',
    year: 1997,
  },
  {
    id: 'griffith-1',
    quote: "A dream can be what makes you live and what torments you. A dream can breathe life into a man, and then can kill him.",
    character: 'Griffith',
    anime: 'Berserk',
    japaneseQuote: '夢は人を生かし、そして苛む。',
    category: 'philosophy',
    themeColor: 'from-slate-400 to-indigo-600',
    year: 1997,
  },
  {
    id: 'gon-1',
    quote: "You should enjoy the little detours to the fullest. Because that's where you'll find the things more important than what you want.",
    character: 'Ging Freecss',
    anime: 'Hunter x Hunter',
    japaneseQuote: '道草を楽しめ。大いにな。ほしいものより大切なものがきっとそっちで転がってる。',
    category: 'wisdom',
    themeColor: 'from-emerald-500 to-amber-500',
    year: 2011,
  },
  {
    id: 'killua-1',
    quote: "Gon, you are light. Sometimes you shine so brightly, I must look away... Even so, is it still okay if I stay at your side?",
    character: 'Killua Zoldyck',
    anime: 'Hunter x Hunter',
    japaneseQuote: 'ゴン、お前は光だ。時々眩しすぎて見ていられないよ。',
    category: 'emotion',
    themeColor: 'from-indigo-400 to-purple-500',
    year: 2011,
  },
  {
    id: 'mob-1',
    quote: "Having psychic powers doesn't make you any better than anyone else. Being popular or good at sports is just as amazing.",
    character: 'Shigeo Kageyama (Mob)',
    anime: 'Mob Psycho 100',
    japaneseQuote: '超能力があるからって特別じゃない。',
    category: 'wisdom',
    themeColor: 'from-purple-500 to-emerald-400',
    year: 2016,
  },
  {
    id: 'reigen-1',
    quote: "When things go wrong, it's okay to run away! Running away isn't weakness, it's choosing to fight another day.",
    character: 'Arataka Reigen',
    anime: 'Mob Psycho 100',
    japaneseQuote: '嫌な時は逃げたっていいんだよ！',
    category: 'wisdom',
    themeColor: 'from-amber-400 to-orange-600',
    year: 2016,
  },
  {
    id: 'denji-1',
    quote: "Everyone has some grand dream, but all I want is jam on toast, a soft bed, and someone who actually cares about me.",
    character: 'Denji',
    anime: 'Chainsaw Man',
    japaneseQuote: '俺の夢は…普通の暮らしがしたいだけなんだ。',
    category: 'emotion',
    themeColor: 'from-orange-500 to-rose-600',
    year: 2022,
  },
  {
    id: 'makima-1',
    quote: "Necessary evils are always calculated for the greater good of society.",
    character: 'Makima',
    anime: 'Chainsaw Man',
    japaneseQuote: '必要悪というものは常に管理されているのです。',
    category: 'philosophy',
    themeColor: 'from-rose-600 to-amber-700',
    year: 2022,
  },
  {
    id: 'jinwoo-1',
    quote: "I will stop at nothing. From the weakest hunter of all mankind to the Monarch of Shadows — Arise!",
    character: 'Sung Jin-woo',
    anime: 'Solo Leveling',
    japaneseQuote: '起きろ（起き上がりたまえ）。',
    category: 'battle',
    themeColor: 'from-indigo-600 to-purple-800',
    year: 2024,
  },
  {
    id: 'saitama-1',
    quote: "Human beings are strong because we have the ability to change ourselves.",
    character: 'Saitama',
    anime: 'One Punch Man',
    japaneseQuote: '人間は自分自身を変える強さを持っている。',
    category: 'determination',
    themeColor: 'from-yellow-400 to-red-600',
    year: 2015,
  },
  {
    id: 'garou-1',
    quote: "The popular will win, the hated will lose, such is the tragedy of life. Then I shall become the absolute monster and change the rules.",
    character: 'Garou',
    anime: 'One Punch Man',
    japaneseQuote: '人気者が勝ち、嫌われ者は負ける。そんな不条理をぶっ壊す！',
    category: 'battle',
    themeColor: 'from-slate-600 to-purple-600',
    year: 2019,
  },
  {
    id: 'allmight-1',
    quote: "It is fine now. Why? Because I am here! Plus Ultra!",
    character: 'All Might',
    anime: 'My Hero Academia',
    japaneseQuote: 'もう大丈夫！なぜって？私が来た！更に向こうへ！プルス・ウルトラ！',
    category: 'determination',
    themeColor: 'from-yellow-500 to-blue-600',
    year: 2016,
  },
  {
    id: 'deku-1',
    quote: "Sometimes I feel like I'm a failure. Like there's no hope for me. But even so, I'm not gonna give up. Ever!",
    character: 'Izuku Midoriya',
    anime: 'My Hero Academia',
    japaneseQuote: '君が救いを求める顔をしてたから…僕は諦めない！',
    category: 'determination',
    themeColor: 'from-emerald-500 to-teal-400',
    year: 2016,
  },
  {
    id: 'violet-1',
    quote: "I want to know what 'I love you' means. I want to understand what warm emotions connect two human souls.",
    character: 'Violet Evergarden',
    anime: 'Violet Evergarden',
    japaneseQuote: '愛してるを…知りたいのです。',
    category: 'emotion',
    themeColor: 'from-emerald-400 to-blue-500',
    year: 2018,
  },
  {
    id: 'kaori-1',
    quote: "Maybe there's only a dark road up ahead. But you still have to believe and keep going. Believe that the stars will light your path.",
    character: 'Kaori Miyazono',
    anime: 'Your Lie in April',
    japaneseQuote: '星が道を照らしてくれると信じて、歩き続けなきゃいけない。',
    category: 'emotion',
    themeColor: 'from-pink-400 to-amber-300',
    year: 2014,
  },
  {
    id: 'kousei-1',
    quote: "Music speaks louder than words. Through our notes, we share the soul we cannot express.",
    character: 'Kousei Arima',
    anime: 'Your Lie in April',
    japaneseQuote: '音は言葉を超える。',
    category: 'emotion',
    themeColor: 'from-sky-400 to-indigo-500',
    year: 2014,
  },
  {
    id: 'gintoki-1',
    quote: "If you have time to fantasize about a beautiful death, why not live beautifully until the very end?",
    character: 'Gintoki Sakata',
    anime: 'Gintama',
    japaneseQuote: '美しく最後を飾りつける暇があるなら、最後まで美しく生きようじゃねぇか。',
    category: 'philosophy',
    themeColor: 'from-sky-400 to-slate-600',
    year: 2006,
  },
  {
    id: 'subaru-1',
    quote: "I have no strength, but I want it all. I have no knowledge, but all I do is dream. There's nothing I can do, but I struggle in vain anyway!",
    character: 'Natsuki Subaru',
    anime: 'Re:Zero - Starting Life in Another World',
    japaneseQuote: 'ゼロから始めよう。ここから、俺の物語を！',
    category: 'determination',
    themeColor: 'from-purple-600 to-orange-500',
    year: 2016,
  },
  {
    id: 'rem-1',
    quote: "From here, let's start from one... No, from zero! Even if the world turns against you, I believe in you.",
    character: 'Rem',
    anime: 'Re:Zero - Starting Life in Another World',
    japaneseQuote: 'ここから、始めましょう。１から…いいえ、ゼロから！',
    category: 'emotion',
    themeColor: 'from-sky-400 to-blue-500',
    year: 2016,
  },
  {
    id: 'jojo-1',
    quote: "Your next line will be: 'How did he predict what I was going to say?!'",
    character: 'Joseph Joestar',
    anime: "JoJo's Bizarre Adventure",
    japaneseQuote: 'お前の次のセリフは…「なぜ分かった？！」という！',
    category: 'battle',
    themeColor: 'from-purple-600 to-pink-500',
    year: 2012,
  },
  {
    id: 'jotaro-1',
    quote: "Yare yare daze. There is only one reason you lost: you really pissed me off.",
    character: 'Jotaro Kujo',
    anime: "JoJo's Bizarre Adventure: Stardust Crusaders",
    japaneseQuote: 'やれやれだぜ。てめーの敗因はたったひとつだ…てめーはおれを怒らせた。',
    category: 'battle',
    themeColor: 'from-indigo-600 to-slate-800',
    year: 2014,
  },
  {
    id: 'anya-1',
    quote: "Anya loves peanuts! I want world peace so Papa, Mama, and I can always have fun together!",
    character: 'Anya Forger',
    anime: 'Spy x Family',
    japaneseQuote: 'アーニャ、ピーナッツが好き！せかいへいわ！',
    category: 'emotion',
    themeColor: 'from-pink-400 to-amber-300',
    year: 2022,
  },
  {
    id: 'isagi-1',
    quote: "I will rewrite my own football equation. If I can't adapt, I'll evolve into the ultimate egoist!",
    character: 'Yoichi Isagi',
    anime: 'Blue Lock',
    japaneseQuote: '俺のゴールで勝つ！エゴを解き放て！',
    category: 'determination',
    themeColor: 'from-blue-500 to-emerald-400',
    year: 2022,
  },
  {
    id: 'hinata-1',
    quote: "A tall wall stands before me. What does the view from above look like? It's a view I can never see on my own.",
    character: 'Shoyo Hinata',
    anime: 'Haikyu!!',
    japaneseQuote: '目の前に立ちはだかる高い高い壁。その向こうはどんな眺めだろうか。',
    category: 'determination',
    themeColor: 'from-orange-500 to-amber-400',
    year: 2014,
  },
  {
    id: 'kaneki-1',
    quote: "It's better to be hurt than to hurt others. Kind people can be happy with just that.",
    character: 'Ken Kaneki',
    anime: 'Tokyo Ghoul',
    japaneseQuote: '傷つけるより傷つけられる人でありたい。',
    category: 'philosophy',
    themeColor: 'from-red-600 to-slate-800',
    year: 2014,
  },
  {
    id: 'bocchi-1',
    quote: "Even if I can only play guitar in the dark of my closet, music is the one place where my introverted heart can scream.",
    character: 'Hitori Gotoh (Bocchi)',
    anime: 'Bocchi the Rock!',
    japaneseQuote: '陰キャならロックをやれ！',
    category: 'emotion',
    themeColor: 'from-pink-400 to-rose-500',
    year: 2022,
  },
  {
    id: 'senku-1',
    quote: "There's nothing you can't do if you try. That's the rules of science: 10 billion percent guaranteed!",
    character: 'Senku Ishigami',
    anime: 'Dr. Stone',
    japaneseQuote: '唆るぜ、これは！100億％科学の勝利だ！',
    category: 'wisdom',
    themeColor: 'from-emerald-500 to-yellow-400',
    year: 2019,
  },
  {
    id: 'rudy-1',
    quote: "In this second life, I will not look back with regret. I will run with everything I have.",
    character: 'Rudeus Greyrat',
    anime: 'Mushoku Tensei: Jobless Reincarnation',
    japaneseQuote: '今度こそ本気で生きてやる。',
    category: 'determination',
    themeColor: 'from-amber-600 to-emerald-600',
    year: 2021,
  },
  {
    id: 'david-1',
    quote: "I'm going to the top of Arasaka Tower. For you, Lucy.",
    character: 'David Martinez',
    anime: 'Cyberpunk: Edgerunners',
    japaneseQuote: '君を月へ連れて行くよ。',
    category: 'emotion',
    themeColor: 'from-yellow-400 to-cyan-400',
    year: 2022,
  },
  {
    id: 'ai-hoshino-1',
    quote: "Lies are an exceptional form of love! In this world, illusions given with passion become real magic.",
    character: 'Ai Hoshino',
    anime: 'Oshi no Ko',
    japaneseQuote: '嘘はとびきりの愛なんだよ！',
    category: 'emotion',
    themeColor: 'from-pink-500 to-purple-600',
    year: 2023,
  },
  {
    id: 'shinji-1',
    quote: "I musn't run away. I musn't run away. I musn't run away!",
    character: 'Shinji Ikari',
    anime: 'Neon Genesis Evangelion',
    japaneseQuote: '逃げちゃダメだ。逃げちゃダメだ。逃げちゃダメだ！',
    category: 'determination',
    themeColor: 'from-purple-600 to-emerald-500',
    year: 1995,
  },
  {
    id: 'misato-1',
    quote: "Miracles don't just happen. People make them happen.",
    character: 'Misato Katsuragi',
    anime: 'Neon Genesis Evangelion',
    japaneseQuote: '奇跡は待つものじゃない。起こすものよ。',
    category: 'wisdom',
    themeColor: 'from-indigo-600 to-rose-500',
    year: 1995,
  },
  {
    id: 'goku-1',
    quote: "Power comes in response to a need, not a desire. You have to create that need!",
    character: 'Son Goku',
    anime: 'Dragon Ball Z',
    japaneseQuote: 'オラは地球育ちのサイヤ人、孫悟空だ！',
    category: 'determination',
    themeColor: 'from-amber-500 to-orange-600',
    year: 1989,
  },
  {
    id: 'vegeta-1',
    quote: "There is only one certainty in life: a strong man stands above and conquers all!",
    character: 'Vegeta',
    anime: 'Dragon Ball Z',
    japaneseQuote: 'オレはサイヤ人の王子、ベジータ様だ！',
    category: 'battle',
    themeColor: 'from-blue-600 to-indigo-700',
    year: 1989,
  },
  {
    id: 'ichigo-1',
    quote: "If fate is a millstone, then we are the grist. There is nothing we can do... So long as I have the blade to shatter fate!",
    character: 'Ichigo Kurosaki',
    anime: 'Bleach',
    japaneseQuote: '運命が歯車なら、俺達はそれを粉砕する刃だ。',
    category: 'battle',
    themeColor: 'from-orange-500 to-slate-800',
    year: 2004,
  },
  {
    id: 'aizen-1',
    quote: "Admiration is the furthest thing from understanding.",
    character: 'Sosuke Aizen',
    anime: 'Bleach',
    japaneseQuote: '憧れは、理解から最も遠い感情だよ。',
    category: 'philosophy',
    themeColor: 'from-indigo-700 to-slate-900',
    year: 2004,
  },
  {
    id: 'alucard-1',
    quote: "A bird in the hand is worth two in the bush. But what happens when the bird has fangs?",
    character: 'Alucard',
    anime: 'Hellsing Ultimate',
    japaneseQuote: '化け物を倒すのはいつだって人間だ。',
    category: 'battle',
    themeColor: 'from-red-700 to-slate-950',
    year: 2006,
  },
  {
    id: 'vash-1',
    quote: "This world is made of love and peace! No one has the right to take the life of another.",
    character: 'Vash the Stampede',
    anime: 'Trigun',
    japaneseQuote: 'ラブ＆ピース！この世に無駄な命など一つもない！',
    category: 'freedom',
    themeColor: 'from-red-600 to-yellow-500',
    year: 1998,
  },
  {
    id: 'johann-1',
    quote: "Tell me, Doctor Tenma... which of us was the monster?",
    character: 'Johan Liebert',
    anime: 'Monster',
    japaneseQuote: '人間の命が平等なのは、死の瞬間だけだ。',
    category: 'philosophy',
    themeColor: 'from-slate-700 to-slate-950',
    characterAvatar: 'https://s4.anilist.co/file/anilistcdn/character/large/b724-GFGgI9AJQkfy.jpg',
    year: 2004,
  },
  {
    id: 'tenma-1',
    quote: "All human lives are created equal. You cannot weigh one life against another.",
    character: 'Dr. Kenzo Tenma',
    anime: 'Monster',
    japaneseQuote: 'すべての命は平等だ。',
    category: 'wisdom',
    themeColor: 'from-emerald-600 to-slate-700',
    characterAvatar: 'https://s4.anilist.co/file/anilistcdn/character/large/b718-b6ZZVp822lw0.png',
    year: 2004,
  },
];

/**
 * Returns today's deterministic Quote of the Day on a 12-hour automatic cycle.
 * Rotates automatically every 12 hours (e.g. 00:00 - 12:00, 12:00 - 24:00).
 * User cannot refresh it manually.
 */
export function getTwelveHourQuote(): {
  quote: AnimeQuote;
  slotId: number;
  periodLabel: string;
  nextUpdateInMs: number;
} {
  const now = Date.now();
  const TWELVE_HOURS = 12 * 60 * 60 * 1000;
  const currentSlot = Math.floor(now / TWELVE_HOURS);
  const nextSlotTime = (currentSlot + 1) * TWELVE_HOURS;
  const nextUpdateInMs = Math.max(0, nextSlotTime - now);

  const total = ANIME_QUOTES_DATABASE.length;
  // Multiplicative hash to smoothly jump across different anime/characters each 12-hour cycle
  const slotIndex = ((currentSlot * 17) % total + total) % total;
  const quote = ANIME_QUOTES_DATABASE[slotIndex] || ANIME_QUOTES_DATABASE[0];

  const date = new Date(now);
  const isPM = date.getHours() >= 12;
  const periodLabel = `${date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} (${isPM ? '12h PM' : '12h AM'})`;

  return {
    quote,
    slotId: currentSlot,
    periodLabel,
    nextUpdateInMs,
  };
}

/**
 * Legacy alias for backwards compatibility
 */
export function getQuoteOfTheDay(forcedOffset: number = 0): {
  quote: AnimeQuote;
  dateStr: string;
  dayIndex: number;
  totalQuotes: number;
} {
  const { quote, periodLabel } = getTwelveHourQuote();
  return {
    quote,
    dateStr: periodLabel,
    dayIndex: 1,
    totalQuotes: ANIME_QUOTES_DATABASE.length,
  };
}

/**
 * Get a random quote that is guaranteed different from current ID
 */
export function getRandomDifferentQuote(currentId?: string): AnimeQuote {
  const pool = ANIME_QUOTES_DATABASE.filter(q => q.id !== currentId);
  const randomIndex = Math.floor(Math.random() * pool.length);
  return pool[randomIndex] || ANIME_QUOTES_DATABASE[0];
}
