// 100% Verified Working AniList CDN Portraits for Quote of the Day
export const QUOTE_CHARACTER_IMAGES: Record<string, string> = {
  "Monkey D. Luffy": "https://s4.anilist.co/file/anilistcdn/character/large/b40-MNypXsxSRb1R.png",
  "Roronoa Zoro": "https://s4.anilist.co/file/anilistcdn/character/large/b62-S7oAeA9WInjV.png",
  "Frieren": "https://s4.anilist.co/file/anilistcdn/character/large/b176754-PCnpqIOkjhFk.png",
  "Himmel the Hero": "https://s4.anilist.co/file/anilistcdn/character/large/b184311-wQFySqYXEqf1.png",
  "Himmel": "https://s4.anilist.co/file/anilistcdn/character/large/b184311-wQFySqYXEqf1.png",
  "Satoru Gojo": "https://s4.anilist.co/file/anilistcdn/character/large/b127691-9zqh1xpIubn7.png",
  "Yuji Itadori": "https://s4.anilist.co/file/anilistcdn/character/large/b127212-FVm2tD0erQ5B.png",
  "Eren Yeager": "https://s4.anilist.co/file/anilistcdn/character/large/b40882-dsj7IP943WFF.jpg",
  "Erwin Smith": "https://s4.anilist.co/file/anilistcdn/character/large/b46496-Mu86MENd5wNB.png",
  "Levi Ackerman": "https://s4.anilist.co/file/anilistcdn/character/large/b45627-CR68RyZmddGG.png",
  "Light Yagami": "https://s4.anilist.co/file/anilistcdn/character/large/b80-26EhwSsSqQ50.png",
  "L Lawliet": "https://s4.anilist.co/file/anilistcdn/character/large/b71-1W4panC53vfs.png",
  "Edward Elric": "https://s4.anilist.co/file/anilistcdn/character/large/b11-TA5Nuk7EDUZG.jpg",
  "Roy Mustang": "https://s4.anilist.co/file/anilistcdn/character/large/b68-moBLY2WO2am3.png",
  "Madara Uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b53901-HnRKSoHMG5Vg.png",
  "Naruto Uzumaki": "https://s4.anilist.co/file/anilistcdn/character/large/b17-phjcWCkRuIhu.png",
  "Itachi Uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b14-9Kb1E5oel1ke.png",
  "Jiraiya": "https://s4.anilist.co/file/anilistcdn/character/large/b2423-RO5MyoXSA9OL.png",
  "Tanjiro Kamado": "https://s4.anilist.co/file/anilistcdn/character/large/b126071-BTNEc1nRIv68.png",
  "Kyojuro Rengoku": "https://s4.anilist.co/file/anilistcdn/character/large/b129133-VlTPowwt68rJ.png",
  "Spike Spiegel": "https://s4.anilist.co/file/anilistcdn/character/large/b1-ChxaldmieFlQ.png",
  "Lelouch vi Britannia": "https://s4.anilist.co/file/anilistcdn/character/large/b417-gVLmIJu9phcK.png",
  "Kamina": "https://s4.anilist.co/file/anilistcdn/character/large/b2075-sWb5Xz76JWdX.png",
  "Rintaro Okabe": "https://s4.anilist.co/file/anilistcdn/character/large/b35252-DY9TW6pusqeh.png",
  "Makise Kurisu": "https://s4.anilist.co/file/anilistcdn/character/large/b34470-Jw2LXZBL5R8i.png",
  "Thors Snorresson": "https://s4.anilist.co/file/anilistcdn/character/large/b13021-XJAVDHwMWek2.png",
  "Guts": "https://s4.anilist.co/file/anilistcdn/character/large/b422-XTaiTuvRohsV.png",
  "Griffith": "https://s4.anilist.co/file/anilistcdn/character/large/b424-Jfrsf8I7zBps.png",
  "Garou": "https://s4.anilist.co/file/anilistcdn/character/large/b89277-xBGb4B5YISXg.png",
  "Ging Freecss": "https://s4.anilist.co/file/anilistcdn/character/large/26-VpZXIwOdcz8p.jpg",
  "Killua Zoldyck": "https://s4.anilist.co/file/anilistcdn/character/large/b27-Z5O02kQUydpT.jpg",
  "Shigeo Kageyama (Mob)": "https://s4.anilist.co/file/anilistcdn/character/large/b89616-dXmdOc7L6SDi.png",
  "Arataka Reigen": "https://s4.anilist.co/file/anilistcdn/character/large/b89334-OPj1hCzvrt7X.png",
  "Denji": "https://s4.anilist.co/file/anilistcdn/character/large/b130102-FO1VHNnEnLlB.png",
  "Makima": "https://s4.anilist.co/file/anilistcdn/character/large/b137080-UHcynYNjb5ZU.png",
  "Sung Jin-woo": "https://s4.anilist.co/file/anilistcdn/character/large/b129928-BCEjVaP0AQSw.png",
  "Saitama": "https://s4.anilist.co/file/anilistcdn/character/large/b73935-ON5d0mAcrItd.jpg",
  "All Might": "https://s4.anilist.co/file/anilistcdn/character/large/b89086-8Zl07RK7PHoj.jpg",
  "Izuku Midoriya": "https://s4.anilist.co/file/anilistcdn/character/large/b89028-8w1I9o1ISHMg.png",
  "Violet Evergarden": "https://s4.anilist.co/file/anilistcdn/character/large/b90169-4wr1Zehnsac8.png",
  "Kaori Miyazono": "https://s4.anilist.co/file/anilistcdn/character/large/88168.jpg",
  "Kousei Arima": "https://s4.anilist.co/file/anilistcdn/character/large/n88167-2o1ud5h9druu.png",
  "Gintoki Sakata": "https://s4.anilist.co/file/anilistcdn/character/large/b672-cP5VPriN67xJ.png",
  "Natsuki Subaru": "https://s4.anilist.co/file/anilistcdn/character/large/b88573-F8yMTK9GhnTA.png",
  "Subaru Natsuki": "https://s4.anilist.co/file/anilistcdn/character/large/b88573-F8yMTK9GhnTA.png",
  "Rem": "https://s4.anilist.co/file/anilistcdn/character/large/b88575-Ayu8UPDA8NS6.png",
  "Joseph Joestar": "https://s4.anilist.co/file/anilistcdn/character/large/b6356-RImEfUfHpC58.png",
  "Jotaro Kujo": "https://s4.anilist.co/file/anilistcdn/character/large/b4003-gWDSEGbeOAll.png",
  "Anya Forger": "https://s4.anilist.co/file/anilistcdn/character/large/b138100-4Li0tWRCa5bQ.png",
  "Yoichi Isagi": "https://s4.anilist.co/file/anilistcdn/character/large/b142168-QnZeM2FqvZ28.jpg",
  "Shoyo Hinata": "https://s4.anilist.co/file/anilistcdn/character/large/b64893-dlSAcpOnjiTn.png",
  "Ken Kaneki": "https://s4.anilist.co/file/anilistcdn/character/large/b87275-mb13EWZBdbh3.png",
  "Hitori Gotoh (Bocchi)": "https://s4.anilist.co/file/anilistcdn/character/large/b257562-Ru35NYPfsqhY.png",
  "Senku Ishigami": "https://s4.anilist.co/file/anilistcdn/character/large/b124142-XUO1g7wRqkaT.png",
  "Rudeus Greyrat": "https://s4.anilist.co/file/anilistcdn/character/large/b88348-bIe5XnXdRpmX.png",
  "David Martinez": "https://s4.anilist.co/file/anilistcdn/character/large/b284158-z1uGKC3IYVa1.png",
  "Ai Hoshino": "https://s4.anilist.co/file/anilistcdn/character/large/b172759-cccVhJ2fQA92.png",
  "Shinji Ikari": "https://s4.anilist.co/file/anilistcdn/character/large/b89-ZtZhXkh1rITn.png",
  "Misato Katsuragi": "https://s4.anilist.co/file/anilistcdn/character/large/b1259-afTQkZ5SVMOn.png",
  "Son Goku": "https://s4.anilist.co/file/anilistcdn/character/large/246-wsRRr6z1kii8.png",
  "Vegeta": "https://s4.anilist.co/file/anilistcdn/character/large/b913-NIFkKazWM8VO.png",
  "Ichigo Kurosaki": "https://s4.anilist.co/file/anilistcdn/character/large/b5-a7bkJgjhhigE.png",
  "Sosuke Aizen": "https://s4.anilist.co/file/anilistcdn/character/large/b1057-Q0Qtx9p3B28w.png",
  "Alucard": "https://s4.anilist.co/file/anilistcdn/character/large/n601-CVySkaFQgsPW.jpg",
  "Vash the Stampede": "https://s4.anilist.co/file/anilistcdn/character/large/b643-nHYwe1Dm7XoR.jpg",
  "Johan Liebert": "https://s4.anilist.co/file/anilistcdn/character/large/b724-GFGgI9AJQkfy.jpg",
  "Dr. Kenzo Tenma": "https://s4.anilist.co/file/anilistcdn/character/large/b718-b6ZZVp822lw0.png",
  "Kenzo Tenma": "https://s4.anilist.co/file/anilistcdn/character/large/b718-b6ZZVp822lw0.png",
  "Kenzou Tenma": "https://s4.anilist.co/file/anilistcdn/character/large/b718-b6ZZVp822lw0.png"
};
